prgrms-web-devcourse/Team_09_p2p_FE

- src/components/atom/Icon/types.ts
- src/components/common/index.ts
- src/pages/course/create/index.tsx
closes #40 
- develop branch에서 CloseIcon과 PlusIcon을 못 불러오는 문제가 있었습니다.
- 조치사항
- `src/components/atom/Icon/types.ts` 파일에 해당 아이콘에 대한 경로를 추가했습니다.
- before
- after
> hotfix: 변경된 아이콘 경로 재설정

- src/components/common/index.ts
- src/components/domain/CourseCreate/RegionSelect/index.tsx
- src/components/domain/CourseCreate/SearchArea/PlusIcon.tsx
- src/components/domain/CourseCreate/SelectedArea/CloseIcon.tsx
- src/pages/course/create/index.tsx
closes #42 
- 코스 등록 페이지 진입 시 생성되는 모달 페이지를 구현했습니다.
case
1. 지역 선택 후 `지역선택완료` 버튼 클릭 시 모달창 닫힌 후 Step1에 지역 데이터 반영
2. 지역 미선택 후 `지역선택완료` 버튼 클릭 시 `지역을 선택해주세요!` alert 호출
3. 우상단 X 아이콘 선택 시 Router.back() 을 호출하여 이전 페이지로 이동 (이 부분은 Icon 컴포넌트에 onClick 추가 반영될때 구현하겠습니다.)
> feat: 코스 등록 페이지 지역 선택 모달 구현

- public/assets/icons/arrow-down.svg
- src/components/atom/Button/index.tsx
- src/components/atom/Icon/types.ts
- src/pages/place/detail/[postId].tsx
- src/pages/place/detail/index.tsx
- src/types/index.ts
closes #26 
1. 장소 상세페이지 (`/place/detail/:postId`) 를 구현했습니다.
2. 더미데이터 2개를 넣어놓았고, 비동기 로직(더미)을 추가해서 없는 post에 접근하면 404 페이지로 가도록 했습니다.
3. 이미 구현된 `<CourseList>` 컴포넌트를 그대로 사용했는데 size가 맞지 않아서 props로 사이즈를 조절할 수 있으면 좋을 것 같습니다.
> Feature/#26 - 장소 상세페이지 구현

- src/components/domain/SignupForm/Fields/EmailField.tsx
- src/components/domain/SignupForm/Fields/NicknameField.tsx
- src/pages/signup/index.tsx
- src/service/core/WebStorage.ts
- src/service/domains/user.ts
closes #85 
1. 회원가입 성공 시 로그인화면으로 보내는 알림을 추가했습니다.
2. 이메일/닉네임 중복체크하는 api를 연결했습니다.
> feat: 회원가입 성공 시 로그인 화면으로 전환, 이메일/닉네임 중복체크 기능 추가

- src/components/common/CourseList/CourseItem.tsx
- src/components/common/CourseList/index.tsx
- src/components/common/PlaceList/PlaceItem.tsx
- src/components/common/PlaceList/index.tsx
- src/components/domain/UserInfo/MyBookmarks/index.tsx
- src/components/domain/UserInfo/ProfileCard/index.tsx
- src/components/domain/UserInfo/Tab/TabItem.tsx
- src/components/domain/UserInfo/Tab/index.tsx
- src/pages/userinfo/[id]/index.tsx
- src/types/course.ts
- src/types/place.ts
- src/utils/dummydata.ts
closes #80 
- 유저 페이지의 북마크 탭 클릭 시 여행코스와 장소를 따로 분리해서 확인할 수 있도록 변경하였습니다
- 유저 정보 페이지에 더미데이터로 본인페이지와 타인페이지를 구분할 수 있게 로직을 작성해두었습니다.
- PlaceItem도 외부 컨테이너로 size를 조절할 수 있게 px이 아닌 %로 구현하고 grid props를 추가했습니다.
- PlaceItem도 courseItem과 마찬가지로 hover style 및 link 연결 추가했습니다.
> feat: MyBookmarks 컴포넌트 구현

- src/components/domain/Map/CourseMap/index.tsx
- src/pages/course/[id]/index.tsx
- src/pages/course/create/step2/index.tsx
closes #99 
- 전달받는 course 객체 배열의 키값 백엔드 API와 통일
- IPlace type Guard 추가
- 전달 받는 위도, 경도 type 모두 string으로 통일 후 CourseMap 컴포넌트에서 string to number 처리
> fix: CourseMap 컴포넌트 Props 및 내부 로직 수정

- src/components/common/SelectRegion/index.tsx
- src/components/common/SelectTags/index.tsx
- src/pages/index.tsx
- src/pages/search/[keyword].tsx
closes #96
closes #25 
1. 검색 api 호출은 search 페이지의 url을 통해 일어납니다.
2. 헤더의 검색바를 통해 검색하는 기능을 구현했습니다. `keyword`를 통해 search 페이지로 이동됩니다.
3. 메인페이지의 검색바도 `keyword`를 통해 search 페이지로 이동시킵니다.
4. 아직 셀렉트 기능은 구현하지 않았는데 셀렉트 컴포넌트 자체에서 state를 가지고 있어 페이지 이동이 일어나는 상황이 아니면 선택된 태그가 변하지 않았습니다. 따라서 태그를 초기화 시키는 어떤 상태(trigger)를 `toInitializeTrigger` 속성에 집어넣어서 그 상태가 변할 때 초기화 되도록 했습니다.
> feat: 검색기능 구현

- next.config.js
- src/components/common/DetailSidebar/index.tsx
- src/components/domain/CourseDetail/CourseDetailList/index.tsx
- src/components/domain/CourseDetail/CourseOverview/OverviewDetailItem.tsx
- src/components/domain/CourseDetail/CourseOverview/OverviewItem.tsx
- src/components/domain/CourseDetail/CourseOverview/index.tsx
- src/components/domain/CourseSlider/index.tsx
- src/components/domain/Map/CourseMap/index.tsx
- src/pages/course/[id]/index.tsx
- src/pages/place/[postId].tsx
- src/service/domains/course.ts
- src/service/domains/likes.ts
- src/types/course.ts
- src/types/place.ts
closes #97 
- 코스 상세페이지 API 연결하였습니다.
- 존재하지 않는 코스 페이지 접근 시 (api로 받는 값이 없을 경우) 메인 페이지로 이동됩니다.
- 로그인하지 않은 상태에서 좋아요/북마크 버튼 클릭 시 login페이지로 이동됩니다.
- 
- 좋아요/북마크 클릭 시 버튼색상 변경, count 변경이 되지만
API는 수정이 필요하여 백엔드에 요청한 상태이기 때문에 연결은 추후 구현할 예정입니다.
-> 추후 구현하면서 장소 상세에서도 사용할 수 있게 변경 처리할 예정입니다
- types/course , types/place 경로에  type추가해두었습니다.
- data의 interface의 경우 앞에 I를 붙여서 중복되지않게 맞추는게 좋을 것 같습니다.
> feat: 코스 상세페이지 API 연결

- src/components/atom/Image/index.tsx
- src/components/atom/Text/index.tsx
- src/components/atom/Title/index.tsx
- src/components/common/CourseList/CourseItem.tsx
- src/components/domain/CourseDetail/CourseDetailList/index.tsx
- src/components/domain/CourseDetail/CourseOverview/OverviewDetailItem.tsx
- src/components/domain/CourseSlider/CourseSliderItem.tsx
- src/components/domain/CourseSlider/index.tsx
- src/pages/course/[id]/index.tsx
- src/styles/globals.css
- src/utils/converter.ts
closes #110 
- 코스 상세페이지에 장소 image 연결
- 서버에서 받은 날짜 데이터가 slice되서 노출되도록 변경
- 코스 이미지가 정해진 크기에 맞게 출력되도록 변경.
- 코스 상세페이지에서 텍스트가 많아서 글이 줄바꿈되지 않고 텍스트가 초과되는 부분 등
레이아웃 어긋나는부분 수정했습니다.
- Text 컴포넌트가 paragraph설정이 되지 않아 내부 코드를 변경하였습니다.
* 기존과 변경된 점: styled(Text)로 컴포넌트를 만들 경우 Text 컴포넌트의 style이 적용됩니다.
예시)
```javascript
<StyledText color="main></StyledText >
const StyledText = styled(Text)`
color: red; // 적용 안됨
`
```
- custom image 컴포넌트 height 지정 후 이미지 비율 맞출 수 있도록 height, cover props 추가
: 컨테이너에 height 적용하고 아래처럼 사용하면 이미지 일그러짐 없이 사용 가능합니다.
- 기타 css style 적용 했습니다.
> feat: 코스 상세페이지 말줄임 처리 및 날짜 데이터 변경

- src/components/common/DetailSidebar/index.tsx
- src/pages/course/[id]/index.tsx
- src/pages/place/[postId].tsx
- src/service/domains/bookmark.ts
- src/service/domains/like.ts
- src/service/index.ts
- src/types/index.ts
- src/types/like.ts
closes #109 
- 코스 상세 페이지에 연결 완료했습니다.
- 좋아요/북마크 클릭하여 업데이트 될 때 DetailSidebar 컴포넌트에만 리렌더링 하면 될 것 같아서
부모 컴포넌트에 값을 전달하진 않았습니다.
- 좋아요 클릭 시 count값은 처음에 데이터로 받았던 값에서 증가/감소 됩니다. 
- 장소 페이지에서 사용 시 아래와 같이 사용 가능합니다.
```
<DetailSidebar
likes={detailData.likes} 
id={detailData.id}
defaultLiked={detailData.isLiked}
defaultBookmarked={detailData.isBookmarked}
isLoggedIn={isLoggedIn} // 현재 로그인 상태
type="course" // place로 변경하기
/>
```
> feat: DetailSidebar 좋아요/북마크 API 연결

- src/components/common/ImageUpload/index.tsx
- src/components/domain/CourseCreate/PlaceInformation.tsx
closes #113 
등록한 이미지 파일을 반환해주는 ImageUpload 컴포넌트를 구현했습니다.
- 유저 정보
- 코스 등록
- 코스 수정
```
onImageUpload: 이미지 업로드 후처리 핸들러 전달
imageRef: 이미지 객체를 가리키는 useRef전달
labelId: 페이지의 label과 컴포넌트 input의 id를 매칭시켜주는 id
```
```js
<ProfileAvatar size={143} src={previewImage} />
<ImageUpload
onImageUpload={handleFileOnChange}
imageRef={profileImageRef}
labelId={imageId}
/>
{isMyPage && (
<EditButton>
<label htmlFor={imageId} style={{ cursor: 'pointer' }}>
<Icon size={16} name="pencil" block />
</label>
</EditButton>
)}
```
> feat: ImageUpload 컴포넌트 구현

- src/components/common/SelectTags/index.tsx
- src/components/common/SortFilter/index.tsx
- src/pages/search/[keyword].tsx
- src/service/domains/course.ts
- src/types/course.ts
- src/utils/converter.ts
closes #102 
1. 검색페이지에서 필터링 로직을 구현했습니다.
2. 일단 `search/:keyword` 라우트로 만들었는데, 메인페이지에서 태그를 클릭해서 넘어왔을 때를 생각하니 역시 `search?&...`로만 가야하는게 맞는 것 같기도하고... 어렵네요 ㅜㅜ
3. 일단 태그클릭은 고려하지 않고 구현했습니다.
> feat: 검색페이지 태그 필터링 기능 구현

- src/components/common/ImageUpload/index.tsx
- src/components/domain/CourseCreate/PlaceInformation.tsx
- src/components/domain/UserInfo/ProfileCard/index.tsx
- src/hooks/useUser.ts
- src/pages/userinfo/[id]/index.tsx
- src/service/domains/user.ts
closes #121 
- ProfileCard 컴포넌트에 유저 정보 api 연결하여 해당 유저의 게시물/댓글/북마크 개수를 볼 수 있습니다.
- api에서 email이 전달이 안되어 일단 임시로 birth값을 보여줍니다. (api 수정 시 변경될 예정)
- ImageUpload 컴포넌트를 사용하여 프로필 이미지와 API를 연결했습니다.
- 현재 1MB 이상의 이미지를 등록할 경우 서버에서 에러를 반환하는데
이 부분은 사용자에게 이미지를 받고 클라이언트에서 이미지를 압축하여 올리는 방식으로 개선해야 할 것 같습니다.
> feat: ProfileCard 컴포넌트 API 연결 (프로필이미지 변경, 유저정보 표시)

- src/components/domain/UserInfo/PasswordChangeForm/index.tsx
- src/components/domain/UserInfo/PasswordChangeForm/rules.ts
- src/pages/userinfo/[id]/password.tsx
- src/service/domains/user.ts
- src/types/user.ts
closes #126 
비밀번호 수정 페이지를 구현했습니다. 현재 api에 버그가 있습니다.
1. "수정"은 잘됩니다.
2. 그런데 일단 한번 수정하면 이 후 로그인도 안되고 로그인도 안되니... 다른 모든 로직이 불통이 됩니다. (500에러) 다른 분들은 테스트 하지 말아주세요... 왠지 토큰관련 로직에 문제가 있는 것 같은데 이 부분 키드에게 요청했고 내일 다른 분들께 여쭤볼 필요가 있다고 하셔서 당장 처리는 안될 듯 합니다.
3. 현재 보시는 이미지는 이미 수정을 한번해서(?) 500에러가 나오고 있는 상황입니다. 일단 UI 부분만 봐주시면 감사하겠습니다.
> feat: 비밀번호 수정 페이지 구현

- public/assets/icons/search-blue.svg
- src/components/atom/Button/index.tsx
- src/components/atom/Icon/types.ts
- src/components/atom/PageContainer/index.tsx
- src/components/domain/home/MainCategoryTitle.tsx
- src/pages/index.tsx
- src/styles/theme.ts
- src/utils/constants.ts
closes #136 
- PageContainer의 detail props로 받은 레이아웃의 가로너비가 940->796으로 변경했습니다.
: 작업된 페이지에서 width값 px로 고정해놓으신 경우 한번 확인 부탁드려요!
- 메인페이지 검색 창 focus시 style 추가하고 크기 조정했습니다.
- title sm, md, lg 로 사이즈 지정되어있던 부분 전부 4px씩 조정했습니다.
: 혹시나 직접 size=?px과 같은 형태로 작성하신 분들은 직접 조정이 필요할 듯 합니다.
> ui: PageContainer 크기 수정 및 style 변경

- src/components/domain/SignupForm/Fields/EmailField.tsx
- src/components/domain/SignupForm/Fields/NicknameField.tsx
- src/components/domain/SignupForm/Fields/PasswordCheckField.tsx
- src/components/domain/SignupForm/index.tsx
- src/components/domain/SignupForm/rules.ts
- src/components/domain/UserInfo/EditForm/index.tsx
- src/components/domain/UserInfo/EditForm/rules.ts
- src/pages/signup/index.tsx
- src/pages/userinfo/[id]/edit.tsx
- src/pages/userinfo/[id]/password.tsx
closes #45 
1. UX개선) 사용자에게 이메일, 닉네임 중복검사를 하라는 메시지를 `window.alert`에서 `ErrorMessage`로 개선하였습니다.
2. UX개선) 비밀번호를 입력하고 -> 비밀번호 확인을 입력하고 -> 다시 비밀번호를 변경하였을 때, 비밀번호 확인에 에러메시지가 나타나도록 하였습니다.
3. UX추가) "비밀번호 확인"은 유저가 피드백을 빠르게 받는 것이 좋을 것 같아 `blur` 후 에러메시지를 보이지 않고 바로 에러메시지를 만나도록 하였습니다. 
4. validation 개선) 닉네임에 공백 등 특수문자를 사용하지 못하도록 하는 validation을 추가하였습니다.
> refactor: 회원가입 폼 리팩터링

- src/components/common/Header/index.tsx
- src/components/common/Layout/index.tsx
- src/components/domain/LoginForm/index.tsx
- src/hooks/useUser.ts
- src/pages/index.tsx
- src/pages/login/index.tsx
- src/pages/userinfo/[id]/edit.tsx
- src/pages/userinfo/[id]/password.tsx
- src/recoil/index.ts
- src/service/domains/user.ts
- src/types/place.ts
- src/types/user.ts
closes #154 
- 로그인 실패 시 에러와 함께 페이지가 표시되지 않는 에러를 수정했습니다.
- 로그인 실패 시 에러 메세지를 하단에 표시하도록 변경하였습니다.
- 이 과정에서 로그인 시도 시 상단 헤더의 버튼이 깜빡이는 현상이 발생하여 전역으로 관리하던 isLoading값을 제거하고
따로 layout(header)에서 관리하도록 수정하였습니다.
- 추가로 메인페이지 코스, 장소 인기순으로 보여지도록 변경했습니다.
> fix: 로그인 실패시 에러처리

- public/assets/icons/arrow-left.svg
- public/assets/icons/arrow-right.svg
- src/components/atom/Icon/types.ts
- src/components/common/Comment/CommentItem.tsx
- src/components/domain/CourseSlider/CourseSliderItem.tsx
- src/components/domain/CourseSlider/index.tsx
- src/pages/course/[id]/index.tsx
- src/types/place.ts
closes #157 
: 이제 장소 상세보기 누르면 상세페이지로 연결됩니다
> fix: 코스 상세페이지 수정

- src/components/common/SearchInput/index.tsx
- src/components/common/SelectRegion/index.tsx
- src/components/common/SelectTags/index.tsx
- src/pages/course/index.tsx
- src/pages/index.tsx
- src/pages/place/index.tsx
- src/pages/search/index.tsx
- src/service/domains/place.ts
- src/types/place.ts
- src/utils/converter.ts
closes #153 
보시는 바와 같습니다. 코스페이지, 장소페이지 에서는 라우팅을 유지시킵니다.
아직 검색페이지에는 라우팅을 유지시키지 않았는데 이것도 구현을 해보면 좋겠다는 생각,,
> feat: 코스페이지, 장소페이지, 검색페이지 필터링 기능 구현

- .gitignore
- src/components/common/DetailSidebar/index.tsx
- src/components/common/Layout/index.tsx
- src/components/domain/CourseDetail/KakaoButton/index.tsx
- src/pages/_app.tsx
- src/pages/_document.tsx
closes #161 
- 코스,장소 상세페이지에 공유하기 버튼에 카카오 카카오 API를 사용했습니다.
- 공유하기링크로 들어올 경우 해당 페이지가 아닌 홈으로 접근이 되는데 이부분은 다시 알아보고 적용을 해보겠습니다.
> feat: 카카오톡 공유하기 기능 구현

- src/components/atom/Modal/BackgroundDim.tsx
- src/components/atom/Modal/index.tsx
- src/components/common/Form/FieldMessage.tsx
- src/components/common/Toast/ToastItem.tsx
- src/components/common/Toast/ToastManager.tsx
- src/components/common/Toast/index.tsx
- src/components/common/index.ts
- src/components/domain/LoginForm/index.tsx
- src/components/domain/SignupForm/Fields/BirthField.tsx
- src/components/domain/SignupForm/Fields/EmailField.tsx
- src/components/domain/SignupForm/Fields/NicknameField.tsx
- src/components/domain/SignupForm/Fields/PasswordCheckField.tsx
- src/components/domain/SignupForm/Fields/PasswordField.tsx
- src/components/domain/SignupForm/index.tsx
- src/components/domain/UserInfo/EditForm/index.tsx
- src/components/domain/UserInfo/PasswordChangeForm/index.tsx
- src/components/domain/UserInfo/ProfileCard/index.tsx
- src/hooks/index.ts
- src/hooks/useTimeout.ts
- src/pages/signup/index.tsx
- src/pages/userinfo/[id]/edit.tsx
- src/pages/userinfo/[id]/password.tsx
- src/types/font.ts
closes #13 
PR을 나누지 못해 죄송합니다...ㅜㅜ
1. Toast 컴포넌트를 구현하여 `window.alert` 대신 사용했습니다. 아래는 현재 적용시켜놓은 곳입니다.
- 회원가입 시) ~님 환영합니다! 로그인 해주세요.
- 유저정보변경 시) 정보가 변경되었습니다.
- 비밀번호 변경 시) 비밀번호가 변경되었습니다. // 현재 비밀번호가 올바르지 않습니다. // 현재 비밀번호와 다른 비밀번호로 변경해주세요.
- 로그아웃 시) 로그아웃 되었습니다.
2. Toast가 필요하지 않은 Form Field가 있다고 판단하여 아래는 Toast가 아닌 초록색 메세지를 보여주도록 개선했습니다.
- 이메일 중복확인, 닉네임 중복확인 필드는 초록색 메세지를 보여준다) ~는 사용가능한 메일입니다. // 이미 존재하는 메일입니다.
3. 생년월일 필드에 최솟값(1900-01-01)과 최댓값(2030-12-31)을 적용하였습니다.
4. 비밀번호는 사용자에게 보여지지 않아서 CapsLock이 켜져있다는 것을 알려주면 좋을 것 같아 추가했습니다. (제가 비밀번호를 계속 틀렸는데 캡스락이 켜져있던 거였음...)
> feat: Toast 컴포넌트 구현 및 적용, Form 메세지 UX 리팩터링, 생년월일 필드 리팩터링, 캡스락 경고 추가

- src/components/domain/CourseCreate/RegionSelect/index.tsx
- src/components/domain/Map/SearchMap/index.tsx
- src/pages/course/create/index.tsx
closes #194 
- 지역 선택 Modal 띄우기
- 장소 검색결과 없을 시 alert
- 지역 변경 시 선택된 장소 리스트 초기화
- 장소 리스트 2개 미만일 시 추가 안내 alert
- 토스트 병합 전 브랜치라 토스트 병합 후에 alert 및 confirm 창을 토스트로 적용하겠습니다.
- 지역 변경 시 검색 결과 리스트가 남아있으므로 해당 부분 초기화 작업을 추후 작업으로 진행하겠습니다.
> feat: 코스 등록(step1) 페이지 기능 구현

- src/components/common/CourseList/CourseItem.tsx
- src/components/common/Recommend/index.tsx
- src/pages/course/search/[id].tsx
- src/pages/place/[id].tsx
- src/pages/place/search/[id].tsx
closes #176
- 장소 상세페이지에서 해당 장소가 포함된 코스의 전체보기 클릭 시 이동되는 페이지를 구현했습니다.
- 검색결과 페이지와 코드가 비슷하지만 필터 내용이 없기 때문에 따로 구현을 했습니다.
- 추후 리팩토링 과정에서 합치는 방법을 고려해봐도 좋을 것 같습니다.
- 코스 검색 API로는 장소의 이름을 받을 수 없기 때문에 장소 상세조회 API를 추가했습니다.
> feat: 해당 장소가 포함된 코스 페이지 구현

- src/pages/place/[id].tsx
- src/types/index.ts
closes #215 
장소 상세 페이지에서 카카오 장소 호출 시 잘못된 url을 호출하는 문제가 있어 수정하였습니다.
- before
- after
> hotfix: 장소 상세 페이지에서 카카오 장소 연결 안되는 현상 조치

- src/components/common/Comment/CommentItem.tsx
closes #227 
- 대댓글 프로필 부분 현재 게시글 작성자 profile로 되어있던 부분 현재 로그인 유저 profile로 변경하였습니다.
> fix: 대댓글 프로필 이미지 현재 유저 프로필로 변경

- src/components/common/Layout/index.tsx
- src/components/domain/CourseDetail/KakaoButton/index.tsx
closes #
- kakao init을 하던 위치를 layout이 아닌 KakaoButton 컴포넌트로 이동시키고 script 방어코드를 추가했습니다.
> hotfix: kakao init위치 변경 및 script 방어코드 추가

- src/components/common/Layout/index.tsx
- src/components/common/Spinner/index.tsx
- src/hooks/index.ts
- src/hooks/useRouteChange.ts
- src/pages/_app.tsx
- src/pages/course/index.tsx
- src/pages/place/index.tsx
- src/pages/userinfo/[id]/index.tsx
- src/styles/globals.css
closes #234 
- 페이지 이동 시 spinner가 나타나도록 구현했습니다.
- route가 변경되면 spinner처리를 해두었는데 저희 페이지에서 router.replace 하는 부분도 routing으로 감지가 되어
replace 부분에 shallow 옵션을 추가했습니다.
> feat: 페이지 이동 시 로딩 처리

- src/components/atom/Avatar/index.tsx
- src/components/atom/Button/index.tsx
- src/components/atom/Button/types.ts
- src/components/atom/Image/index.tsx
- src/components/atom/Logo/index.tsx
- src/components/atom/Text/index.tsx
- src/components/atom/Title/index.tsx
- src/components/common/ArrowTitle/index.tsx
- src/components/common/Comment/CommentItem.tsx
- src/components/common/Header/index.tsx
- src/components/common/PlaceList/index.tsx
- src/components/common/SliderContainer/index.tsx
- src/components/common/SliderContainer/types.ts
- src/components/common/Spinner/index.tsx
- src/components/domain/CourseDetail/KakaoButton/index.tsx
- src/components/domain/CourseSlider/index.tsx
- src/components/domain/Place/RelevantCourses.tsx
- src/pages/_document.tsx
- src/pages/course/[id]/index.tsx
- src/pages/index.tsx
closes #238 
- Title 컴포넌트 level 적용 안되던 부분 수정했습니다.
- Button 컴포넌트 내부 코드가 길어져서 types로 분리했습니다.
- image 컴포넌트에 부모요소 relative속성이 없어서 warning 나타나던 부분 수정했습니다.
- 이전에 Slider컴포넌트 중복 코드 작성했던 부분 하나의 컴포넌트로 맞췄습니다.
- 페이지 로딩 시에 현재 scroll위치에 따라 spinner 위치가 달랐었는데 항상 화면 가운데에 나타나도록 수정했습니다.
- Lighthouse에서 제안한 내용에 따라 html에 lang 속성 추가하고 ul태그가 아닌 div로 감싸져 있던 부분 수정했습니다.
> refactor: 공통 컴포넌트 type 분리 및 내부 로직 수정

- src/components/common/PageHead/index.tsx
- src/components/domain/AppHead/index.tsx
- src/pages/_app.tsx
- src/pages/course/[id]/index.tsx
- src/pages/course/index.tsx
- src/pages/course/search/[id].tsx
- src/pages/login/index.tsx
- src/pages/place/[id].tsx
- src/pages/place/index.tsx
- src/pages/search/index.tsx
- src/pages/signup/index.tsx
- src/pages/userinfo/[id]/index.tsx
closes #207 
- 사이트 전체의 head부분을 일괄로 처리했던 부분을 pageHead 컴포넌트를 생성하여
title 변경이 필요한 페이지에 적용하였습니다.
- next head의 경우 기본 mata태그인 title, description의 경우 중첩으로 작성 시 덮어쓰기가 되는데
og태그의 경우 중첩으로 작성 시 덮어쓰기가 아닌 추가가 됩니다.
- 해당 페이지 링크 공유 시 중첩으로 작성한 og:title이 적용되는지는 배포 후에 확인해봐야 할 것 같습니다.
- meta title에 유저 nickname을 넣으려면 데이터를 미리 받아야 하기도 하고
처음 받아오는 데이터는 유저의 기본 정보만 담겨있기 때문에 문제가 없을 듯 하여 SSR을 적용했습니다.
- 뒤로가기 시 데이터 패칭이 되지 않아서 따로 처리하는 코드를 작성했습니다.
> feat: 페이지별 title/description 추가

- src/components/common/Toast/index.tsx
closes #251 
React17까지는 `ReactDOM.render`였지만 18부터 메서드가 지원되지 않게 되었습니다. 따라서 `createRoot` 메서드로 변경했습니다.
> refactor: ReactDOM.render를 createRoot 메서드로 변경

- src/service/core/Api.ts
- src/service/core/workers.ts
closes #149 
Axios 객체에 에러를 캐치하는 함수를 구현하였습니다. 
1. 구현 과정에서 기존 core/Api 클래스 안에 있던 로직을 따로 분리했는데... 좋은건지 안좋은건지 잘 모르겠네영...ㅎㅎ
2. 에러코드에 대해서 캐치를 하는 이 부분에는 조금 연구가 많이 필요할 것 같다랄까... 제가 생각하는 제일 Best는 api를 사용하는 쪽에서 에러핸들링을 하지 않도록 하고 싶었는데(사실 이게 가능한건지, 가능하다면 좋은 방법은 어떤 것일지 고민이 많이 됐습니당..) 현재로서는 500번대 에러에 대해서 알림을 띄우는 것이 최선이었습니다 ㅜㅜ
3. 이번에 axios에 대해서 조금 더 공부하게 된 계기가 됐네요 ㅎㅎ 차차 공부해서 더 좋은 방법을 한번 찾아보려합니다!
> refactor: Axios에서 500번대 에러는 캐치하는 로직 추가
