- src/components/atom/Button/index.tsx
- src/components/atom/Title/index.tsx
- src/pages/userinfo/edit/index.tsx
closes #47 
- input 컴포넌트를 붙일 수 있게 틀만 작업해두었습니다.
> feat: 내 정보 수정페이지 구현

- src/pages/userinfo/password/index.tsx
closes #48
- 정보 수정페이지와 마찬가지로 레이아웃만 구현했습니다.
- 정보 수정 페이지랑 틀이 비슷해서 복사했는데 그루님이 내부 form 및 input 관련 로직 추가해주신 후에
중복되는 것은 분리할 예정입니다.
> feat: 비밀번호 변경 페이지 구현

- src/components/atom/Button/index.tsx
closes #49
- Button disable style, tag hover color 추가했습니다.
- hover시 transition 0.1s로 조금 부드럽게 처리했습니다.
> ui: Button컴포넌트 disabled, hover css 추가 및 수정

- src/components/domain/CourseDetail/CourseDetailList/index.tsx
- src/components/domain/CourseSlider/index.tsx
- src/pages/course/[id]/index.tsx
> feat: 코스 상세페이지 CourseMap 연결

- src/components/domain/CourseCreate/RegionSelect/index.tsx
- src/components/domain/Map/CourseMap/index.tsx
- src/components/domain/Map/PlaceMap/index.tsx
- src/pages/course/create/index.tsx
closes #67 
- ## 선택된 지역 색상 mainColor로 변경
- ## 지도 style  height: 100%로 변경
- ## 코스등록 step1 -> step2 페이지 이동
- ## Kakao API 호출 스크립트 동적 로딩 해결 (unmount 처리)
데모 준비를 위해 빠르게 Merge하겠습니다 🙂🙂
> feat: 코스등록 step1 페이지 UI수정 및 step2 페이지 연결

- src/components/atom/Icon/IconButton.tsx
- src/components/atom/Icon/index.tsx
closes #70 
- button으로 감싸진 Icon.Button 컴포넌트를 구현했습니다.
- 아래와 같이 사용하시면 됩니다.
```
<Icon.Button onClick={} name="" size={}/>
```
> feat: IconButton 컴포넌트 구현

- src/components/common/Header/index.tsx
- src/components/common/Layout/index.tsx
- src/hooks/useUser.ts
- src/recoil/index.ts
- src/types/user.ts
closes #105 
- recoil에서 자동으로 loadingState를 감지하는 부분이 있나 찾아보았는데
토큰 비교를 통해 조건부로 호출하여 loading을 감지하는 적합한 방법을 찾지는 못했습니다.
일단 setState를 사용하듯  isLoading값을 추가하여 loading을 감지할 수 있도록 하였습니다.
- 추후 좀더 나은 방법을 찾게되면 다시 개선을 해 볼 예정이며 혹시나 더 나은 방법이 있으시다면 코멘트 부탁드립니다~
> fix: 로그인 상태에서 새로고침 시 로그인 버튼 잠시 보이던 현상 해결

- src/components/domain/CourseCreate/PlaceInformation.tsx
- src/pages/course/create/index.tsx
- src/pages/course/create/step2/index.tsx
- src/service/domains/course.ts
- src/types/index.ts
- src/utils/constants.ts
closes #98 
- ### multipart/form-data 적용 방법
> 만드신 API headers에 객체로 지정해주시면 됩니다.
```js
create = async (formData: FormData) => {
try {
const response = await this.authInstance.post(`${this.path}/`, formData, {
headers: {
'Content-Type': 'multipart/form-data'
}
});
return response.status;
} catch (e) {
console.error(`코스 등록 오류: ${e}`);
}
};  
```
> form data에서 json은 Blob으로, 이미지는 File로 처리해서 append해주시면 됩니다.
```js
formData.append(
'course',
new Blob([uploaderString], {
type: 'application/json'
})
);
const placesImageData: File[] = placesImageDataSetter();
for (let i = 0; i < placesImageData.length; i++) {
formData.append('images', placesImageData[i]);
}
```
- ### 현재 코스 등록 시 상세 페이지 연결이 안되어 메인 페이지로 이동되게 처리하였습니다.
- ### 코스 등록(step2) 페이지 구현 내역
- 미입력 정보 입력 유도 처리
- 코스 제목
- 기간
- 테마
- 장소
- 장소 이미지
- 장소 설명 …
> feat: 코스 등록(step2) 페이지 api 연결

- src/components/atom/Logo/index.tsx
closes #104 
- 로고 경로가 달라서 엑박뜨던 부분 수정했습니다.
> fix: Logo 이미지 경로 수정

- src/components/common/Comment/CommentItem.tsx
- src/components/common/Header/index.tsx
- src/pages/course/[id]/index.tsx
- src/service/domains/course.ts
closes #128 
- 코스 상세페이지 수정, 삭제 버튼 구현했습니다.
- 수정 버튼 클릭 시 경로는 course/[id]/edit 입니다.
+ 댓글 편집 시 편집됨 표시하도록 추가했습니다.
> feat: 코스 상세페이지 수정, 삭제 버튼 연결

- src/components/domain/CourseCreate/PlaceInformation.tsx
- src/components/domain/CourseCreate/RegionSelect/index.tsx
- src/components/domain/Map/CourseMap/index.tsx
- src/components/domain/Map/SearchMap/index.tsx
- src/pages/course/create/index.tsx
- src/pages/course/create/step2/index.tsx
closes #32 
- 장소 목록 삭제 로직을 추가했습니다.
- 장소를 새로 검색하고 마커를 띄울 경우 이전의 마커가 안 지워지는 버그가 있어 수정했습니다.
- 장소 목록 리스트 디자인 적용했습니다.
- 장소 수정 버튼 클릭 시 코스 상태값을 이전 step에서도 유지할 수 있게 연결했습니다.
> feat: 코스 등록 페이지 연결 작업

- src/pages/place/[id].tsx
closes #
- 이전 csr로만 구현했을땐 처음 로그인 전 데이터를 먼저 받아오고 이후에 로그인이 감지되면
로그인 인증된 데이터(isLike/isBookmarked)를 받는 상태였습니다.
- 서버에서 먼저 로그인 하지 않은 유저의 데이터를 받고
이후에 클라이언트에서 로그인이 감지되면 인증된 데이터를 받도록 변경하였습니다,
- 만약 서버에서 유저 인증이 되면 한번에 로그인 인증된 데이터를 받아도 될 듯 한데 이부분은 조금 더 알아보겠습니다.
> feat: 장소 상세페이지 처음 받는 데이터 SSR 처리

- public/assets/icons/close-thin.svg
- src/components/atom/Icon/IconButton.tsx
- src/components/atom/Icon/types.ts
- src/components/common/Header/index.tsx
- src/components/domain/CourseCreate/RegionSelect/index.tsx
- src/components/domain/CourseCreate/SearchArea/PlusIcon.tsx
- src/components/domain/CourseCreate/SelectedArea/CloseIcon.tsx
- src/components/domain/Map/SearchMap/index.tsx
- src/pages/course/create/index.tsx
closes #
- 코스 등록페이지 step1부분 style 수정 + full header 변경했습니다.
> ui: 코스 등록 페이지 step1 style 수정

- package.json
- src/index.d.ts
- src/pages/404.tsx
- yarn.lock
closes #175 
- gif로 불러오기 위해 여기 사이트에서 제공하는 라이브러리를 추가했습니다!
- 구현하면서 useEffect 안에서 Import를 하는 패턴을 처음봤는데(라이브러리 문서에서 Next에서는 이렇게 사용하라고 되어있더라구요) 이게 다이나믹 임포트방식인가 싶네요!(들어만봤던 바로 그 방식)
> feat: 404페이지 구현

- src/components/common/Comment/index.tsx
- src/components/common/CourseList/CourseItem.tsx
- src/components/common/CourseList/index.tsx
- src/components/common/DetailSidebar/index.tsx
- src/components/common/Header/index.tsx
- src/components/domain/Place/RelevantCourses.tsx
> feat: 로그인하지않은 유저의 접근에 대하여 모달로 로그인을 유도한다.

- src/components/domain/Map/CourseMap/index.tsx
closes #209 
컴포넌트 오버레이 위치가 높아 낮추는 작업을 진행했습니다.
- before
- after
> fix: CourseMap 컴포넌트 오버레이 위치 조정

- src/components/domain/Map/SearchMap/index.tsx
- src/pages/course/create/index.tsx
closes #211 
- 장소 리스트 하나 삭제 시 전체 삭제되는 버그를 긴급 건으로 수정 반영합니다.
> hotfix: 장소 리스트 하나 삭제 시 전체 삭제되는 버그 수정

- src/pages/course/[id]/edit/index.tsx
- src/pages/course/create/index.tsx
- src/pages/course/create/step2/index.tsx
closes #221 
코스 등록/수정 안내 confirm을 Toast로 변경하여 긴급 반영합니다.
> hotfix: 코스 등록/수정 안내confirm Toast로 변경

- src/components/common/Layout/index.tsx
- src/components/domain/CourseDetail/KakaoButton/index.tsx
> HotFix: window 객체를 사용할 때 예외처리 추가

- src/utils/storage/LocalStorage.ts
> hotfix: Storage Throw Error 부분 console.log로 변경
